/*
Deployment script for sdtStagingMastek

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "sdtStaging"
:setvar DefaultFilePrefix "sdtStaging"
:setvar DefaultDataPath "E:\SQLDATA\MSSQL11.DEV\Data\"
:setvar DefaultLogPath "F:\SQLLOGS\MSSQL11.DEV\Logs\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
/*
The type for column CustJnyID in table [dbo].[tblJourneyAgentDelegated] is currently  NCHAR (10) NULL but is being changed to  INT NULL. Data loss could occur.
*/

--IF EXISTS (select top 1 1 from [dbo].[tblJourneyAgentDelegated])
--    RAISERROR (N'Rows were detected. The schema update is terminating because data loss might occur.', 16, 127) WITH NOWAIT

GO
/*
The type for column CustJnyID in table [dbo].[tblJourneyCustomer] is currently  NCHAR (10) NOT NULL but is being changed to  INT IDENTITY (1, 1) NOT NULL. Data loss could occur.
*/

--IF EXISTS (select top 1 1 from [dbo].[tblJourneyCustomer])
--    RAISERROR (N'Rows were detected. The schema update is terminating because data loss might occur.', 16, 127) WITH NOWAIT

GO
PRINT N'Dropping [dbo].[tblJourneyCustomer].[I_NC_JnyCust_2]...';


GO
DROP INDEX [I_NC_JnyCust_2]
    ON [dbo].[tblJourneyCustomer];


GO
PRINT N'Dropping [dbo].[tblJourneyCustomer].[I_NC_JnyCust_3]...';


GO
DROP INDEX [I_NC_JnyCust_3]
    ON [dbo].[tblJourneyCustomer];


GO
PRINT N'Dropping [dbo].[DF_JourneyCustomerLink_CreatedDate]...';


GO
ALTER TABLE [dbo].[tblJourneyCustomer] DROP CONSTRAINT [DF_JourneyCustomerLink_CreatedDate];


GO
PRINT N'Dropping [dbo].[FK_JourneyAgentDelegated_JourneyCustomer]...';


GO
ALTER TABLE [dbo].[tblJourneyAgentDelegated] DROP CONSTRAINT [FK_JourneyAgentDelegated_JourneyCustomer];


GO
PRINT N'Dropping [dbo].[FK_JourneyCustomer_Customer]...';


GO
ALTER TABLE [dbo].[tblJourneyCustomer] DROP CONSTRAINT [FK_JourneyCustomer_Customer];


GO
PRINT N'Dropping [dbo].[FK_JourneyCustomer_Journey]...';


GO
ALTER TABLE [dbo].[tblJourneyCustomer] DROP CONSTRAINT [FK_JourneyCustomer_Journey];


GO
PRINT N'Dropping [dbo].[PK_JourneyCustomerLink]...';


GO
ALTER TABLE [dbo].[tblJourneyCustomer] DROP CONSTRAINT [PK_JourneyCustomerLink];


GO
PRINT N'Altering [dbo].[tblJourneyAgentDelegated]...';


GO
ALTER TABLE [dbo].[tblJourneyAgentDelegated] ALTER COLUMN [CustJnyID] INT NULL;


GO
PRINT N'Starting rebuilding table [dbo].[tblJourneyCustomer]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_tblJourneyCustomer] (
    [CustJnyID]      INT      IDENTITY (1, 1) NOT NULL,
    [CustomerID]     INT      NOT NULL,
    [JourneyID]      INT      NOT NULL,
    [StartDate]      DATETIME NOT NULL,
    [EndDate]        DATETIME NULL,
    [Day]            INT      NULL,
    [JourneyOrderBy] INT      NULL,
    [CreatedDate]    DATETIME CONSTRAINT [DF_JourneyCustomerLink_CreatedDate] DEFAULT (getdate()) NOT NULL,
    [CreatedBy]      INT      NULL,
    [UpdatedDate]    DATETIME NULL,
    [UpdatedBy]      INT      NULL,
    CONSTRAINT [tmp_ms_xx_constraint_PK_JourneyCustomerLink] PRIMARY KEY CLUSTERED ([CustJnyID] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[tblJourneyCustomer])
    BEGIN
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_tblJourneyCustomer] ON;
        INSERT INTO [dbo].[tmp_ms_xx_tblJourneyCustomer] ([CustJnyID], [CustomerID], [JourneyID], [StartDate], [EndDate], [Day], [JourneyOrderBy], [CreatedDate], [CreatedBy], [UpdatedDate], [UpdatedBy])
        SELECT   [CustJnyID],
                 [CustomerID],
                 [JourneyID],
                 [StartDate],
                 [EndDate],
                 [Day],
                 [JourneyOrderBy],
                 [CreatedDate],
                 [CreatedBy],
                 [UpdatedDate],
                 [UpdatedBy]
        FROM     [dbo].[tblJourneyCustomer]
        ORDER BY [CustJnyID] ASC;
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_tblJourneyCustomer] OFF;
    END

DROP TABLE [dbo].[tblJourneyCustomer];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_tblJourneyCustomer]', N'tblJourneyCustomer';

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_constraint_PK_JourneyCustomerLink]', N'PK_JourneyCustomerLink', N'OBJECT';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Creating [dbo].[FK_JourneyAgentDelegated_JourneyCustomer]...';


GO
ALTER TABLE [dbo].[tblJourneyAgentDelegated] WITH NOCHECK
    ADD CONSTRAINT [FK_JourneyAgentDelegated_JourneyCustomer] FOREIGN KEY ([CustJnyID]) REFERENCES [dbo].[tblJourneyCustomer] ([CustJnyID]);


GO
PRINT N'Creating [dbo].[FK_JourneyCustomer_Customer]...';


GO
ALTER TABLE [dbo].[tblJourneyCustomer] WITH NOCHECK
    ADD CONSTRAINT [FK_JourneyCustomer_Customer] FOREIGN KEY ([CustomerID]) REFERENCES [dbo].[tblCustomer] ([CustomerID]);


GO
PRINT N'Creating [dbo].[FK_JourneyCustomer_Journey]...';


GO
ALTER TABLE [dbo].[tblJourneyCustomer] WITH NOCHECK
    ADD CONSTRAINT [FK_JourneyCustomer_Journey] FOREIGN KEY ([JourneyID]) REFERENCES [dbo].[tblJourney] ([JourneyID]);


GO
PRINT N'Refreshing [dbo].[vwJourneyAgentDelegate]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[vwJourneyAgentDelegate]';


GO
PRINT N'Refreshing [dbo].[vwJourneyCustomer]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[vwJourneyCustomer]';


GO
PRINT N'Refreshing [dbo].[vwVisitSummary]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[vwVisitSummary]';


GO
PRINT N'Refreshing [mobile].[vwCardPaymentSummary]...';


GO
EXECUTE sp_refreshsqlmodule N'[mobile].[vwCardPaymentSummary]';


GO
PRINT N'Refreshing [mobile].[vwCustomerVisitList]...';


GO
EXECUTE sp_refreshsqlmodule N'[mobile].[vwCustomerVisitList]';


GO
PRINT N'Checking existing data against newly created constraints';


GO
USE [$(DatabaseName)];


GO
ALTER TABLE [dbo].[tblJourneyAgentDelegated] WITH CHECK CHECK CONSTRAINT [FK_JourneyAgentDelegated_JourneyCustomer];

ALTER TABLE [dbo].[tblJourneyCustomer] WITH CHECK CHECK CONSTRAINT [FK_JourneyCustomer_Customer];

ALTER TABLE [dbo].[tblJourneyCustomer] WITH CHECK CHECK CONSTRAINT [FK_JourneyCustomer_Journey];


GO
PRINT N'Update complete.';


GO

